### ISSUE TITLE
Get rid of telemetry

### ISSUE THREAD

**Issue by dglazkov** [dglazkov/tree-builder-builder#76]
We don't actually use telemetry for anything other than launching a browser. It might be good to explore the possibility of just using [Karma](http://karma-runner.github.io/0.12/index.html) (see [karma-telemetry](https://github.com/axemclion/karma-telemetry) as an example) or even porting launchy parts of telemetry to an npm module.

**Comment by shans** [comment]
We also use telemetry for extracting traces, and for running JS in the browser after launching.

At some point soon I'd like to use it to extract statistical profiling data too.

**Comment by shans** [comment]
(see for example telemetry/perf.py and telemetry/layout-perf.py)

**Comment by shans** [comment]
Going to close this as I don't think we can do it right now. Are you OK with that, Dimitri?
