### ISSUE TITLE
Refactor to enable pipelining

### ISSUE THREAD

**Issue by dglazkov** [dglazkov/tree-builder-builder#8]
Now that we have a few readers and writers (and more coming), it seems like a good idea to refactor into a pipelining model, where readers, filters, and writers become independent units that can be chained together. Here are the pieces:

- [ ] tokenizer stream -- a stream of commands that create the DOM tree
- [ ] reader/builder unit -- reads command line arguments, outputs a tokenizer stream
- [ ] filter -- reads a tokenizer stream, outputs another tokenizer stream
- [ ] writer -- reads a tokenizer stream, outputs something else

The reader/builder always go in front, filter always in the middle, writer always at the end.

@addyosmani @shans, WDYT?

**Comment by shans** [comment]
Sounds like a great plan!

One question: how do readers factor in? To save a page I basically had to cut 'n paste the read.js file into the console. Is there a cleaner way of doing this?

**Comment by addyosmani** [comment]
I love it. I also echo @shans comments. The first thing I wanted was an option to automate or more cleanly handle the copy/pasta step for me. 

Remote debugging protocol or something smarter?

**Comment by dglazkov** [comment]
Ah -- I think the reader is this sense is a "thing that reads a JSON file". The `read.js` is not a reader then. It's a capturer :smiley:

We should have it built into Devtools eventually! Yay!

**Comment by shans** [comment]
Ah, got it.

I could have a crack at refactoring gulpfile.js so that a build target is a list of components? Another thing I was thinking is that there's an extra step after 'writer' - 'output'. This makes it easy to capture outputting to console vs. to a file.

**Comment by shans** [comment]
Oh! And readers could do things like synthesize large DOM fragments (i.e. not based on a capture) to do things like randomized testing, etc.

**Comment by dglazkov** [comment]
Yes! Yes! Yes!

**Comment by shans** [comment]
I think this is achieved by #9
